default:
  listen: 8090
  mode: debug
  push_kubernetes: false
  push_images: false

server:
  auth:
    access_key: access_key
    secret_key: secret_key

agent:
  rpc_server: 127.0.0.1:8091
  name: test-agent
  data_dir: /tmp

plugin:
  callback: http://127.0.0.1:8090
  task_id: 20220801
  synced: true
  driver: docker #skopeo or docker

rate_limit:
  user_rate_limit:
    ## 最大存储客户端IP数量
    cap: 200
    ## 单个客户端IP最大令牌数
    capacity: 100
    ## 每次补充令牌数
    quantum: 20
  normal_rate_limit:
    max_requests: 1000
  special_rate_limit:
    rate_limited_path:
      - "/rainbow/search"
    max_requests: 100

mysql:
  host: peng
  user: root
  password: Pixiu868686
  port: 3306
  name: rainbow

redis:
  addr: redis:6379
  password: ""
  db: 0

registry:
  repository: harbor.cloud.pixiuio.com
  namespace: pixiucloud
  username: test
  password: test

kubernetes:
  version: v1.23.6

images:
  - name: nginx
    id: 20220801
    path: docker.io/nginx
    tags:
      - latest
      - v1.0.1
